# Generated by Django 3.2 on 2024-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0006_auto_20240207_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
