# Generated by Django 3.2 on 2024-02-09 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option', '0007_option_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='postoptionvalue',
            name='option_value_extended',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='option.optionvalueextended'),
        ),
    ]
