# Generated by Django 3.2 on 2024-02-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
